#!/bin/bash

# Quick DNS Fix untuk Error ERR_NAME_NOT_RESOLVED
# Jalankan dengan: sudo ./fix-dns.sh

echo "=========================================="
echo "  DNS Fix for ERR_NAME_NOT_RESOLVED"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "⚠️  Please run as root: sudo ./fix-dns.sh"
    exit 1
fi

# Backup existing resolv.conf
if [ -f /etc/resolv.conf ]; then
    cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)
    echo "✅ Backup created: /etc/resolv.conf.backup.*"
fi

# Method 1: Direct resolv.conf edit (works for most systems)
echo ""
echo "[1/3] Setting Google DNS in /etc/resolv.conf..."
cat > /etc/resolv.conf << EOF
# Generated by fix-dns.sh - $(date)
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
EOF
echo "✅ DNS servers configured"

# Method 2: For systems using systemd-resolved
if systemctl is-active --quiet systemd-resolved; then
    echo ""
    echo "[2/3] Configuring systemd-resolved..."
    
    mkdir -p /etc/systemd/resolved.conf.d/
    cat > /etc/systemd/resolved.conf.d/dns.conf << EOF
[Resolve]
DNS=8.8.8.8 8.8.4.4
FallbackDNS=1.1.1.1 1.0.0.1
EOF
    
    systemctl restart systemd-resolved
    echo "✅ systemd-resolved restarted"
fi

# Method 3: Add WhatsApp IPs to /etc/hosts as fallback
echo ""
echo "[3/3] Adding WhatsApp Web to /etc/hosts..."

# Remove old entries
sed -i '/web.whatsapp.com/d' /etc/hosts

# Add new entries (multiple IPs for redundancy)
cat >> /etc/hosts << EOF

# WhatsApp Web - Added by fix-dns.sh
157.240.22.51 web.whatsapp.com
31.13.95.51 web.whatsapp.com
EOF
echo "✅ /etc/hosts updated"

# Test DNS resolution
echo ""
echo "=========================================="
echo "  Testing DNS Resolution"
echo "=========================================="

if ping -c 2 web.whatsapp.com > /dev/null 2>&1; then
    echo "✅ SUCCESS! web.whatsapp.com is reachable"
    echo ""
    echo "You can now run: node ."
else
    echo "⚠️  Still cannot reach web.whatsapp.com"
    echo ""
    echo "Additional troubleshooting:"
    echo "1. Check firewall: sudo iptables -L"
    echo "2. Check internet: ping 8.8.8.8"
    echo "3. Check proxy: env | grep -i proxy"
    echo ""
    echo "If behind proxy, set in your shell:"
    echo "  export HTTP_PROXY=http://proxy:port"
    echo "  export HTTPS_PROXY=http://proxy:port"
fi

echo ""
echo "DNS configuration completed."
echo "Backup saved, you can restore with:"
echo "  sudo cp /etc/resolv.conf.backup.* /etc/resolv.conf"
echo ""
